### ISSUE TITLE
Realtime Playground doesn't work

### ISSUE THREAD

**Issue by ghk829** [livekit-examples/realtime-playground#5]
**I got the 403 error status form WS Server handshake.**

2024-10-03 15:30:41,719 - ERROR livekit.plugins.openai.realtime - failed to connect to OpenAI API S2S
Traceback (most recent call last):
  File "/Users/messi/miniconda3/envs/realtime-playground/lib/python3.9/site-packages/livekit/plugins/openai/realtime/realtime_model.py", line 588, in _main_task
    ws_conn = await self._http_session.ws_connect(
  File "/Users/messi/miniconda3/envs/realtime-playground/lib/python3.9/site-packages/aiohttp/client.py", line 949, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='https://api.openai.com/v1/realtime?model=gpt-4o-realtime-preview-2024-10-01' {"pid": 64760, "job_id": "AJ_mzbDSWeHPhh5"}
2024-10-03 15:30:57,458 - INFO livekit.agents - job exiting {"reason": "room disconnected", "pid": 64724, "job_id": "AJ_NKeQTUkk7heK"}
2024-10-03 15:30:57,457 - DEBUG livekit.agents - shutting down job task {"reason": "room disconnected", "user_initiated": false, "pid": 64724, "job_id": "AJ_NKeQTUkk7heK"}
2024-10-03 15:30:57,457 - DEBUG livekit.agents - http_session(): closing the httpclient ctx {"pid": 64724, "job_id": "AJ_NKeQTUkk7heK"}
2024-10-03 15:33:02,441 - WARNING livekit - livekit::rtc_engine:410:livekit::rtc_engine - received session close: "signal client closed: \"stream closed\"" UnknownReason Resume {"pid": 64760, "job_id": "AJ_mzbDSWeHPhh5"}

**Comment by davidzhao** [comment]
They are a bit delayed in rolling out access: https://x.com/OpenAIDevs/status/1841598369510391851

**Comment by lemonlinger** [comment]
I still encountered this error today.

**Comment by davidzhao** [comment]
access should be rolled out to everyone
